package ru.xander.replicator.listener;

/**
 * @author Alexander Shakhov
 */
public enum AlterType {
    CREATE_TABLE,
    CREATE_TABLE_COMMENT,
    DROP_TABLE,
    ANALYZE_TABLE,
    RENAME_TABLE,

    CREATE_COLUMN,
    CREATE_COLUMN_COMMENT,
    MODIFY_COLUMN,
    DROP_COLUMN,
    RENAME_COLUMN,

    CREATE_PRIMARY_KEY,
    CREATE_IMPORTED_KEY,
    CREATE_CHECK_CONSTRAINT,
    DROP_PRIMARY_KEY,
    DROP_CONSTRAINT,
    ENABLE_CONSTRAINT,
    DISABLE_CONSTRAINT,

    CREATE_INDEX,
    DROP_INDEX,
    ENABLE_INDEX,
    DISABLE_INDEX,

    CREATE_TRIGGER,
    DROP_TRIGGER,
    ENABLE_TRIGGER,
    DISABLE_TRIGGER,

    CREATE_SEQUENCE,
    DROP_SEQUENCE
}
