package ru.xander.replicator.listener;

public enum AlterType {
    CREATE_TABLE,
    CREATE_TABLE_COMMENT,
    DROP_TABLE,
    ANALYZE_TABLE,

    CREATE_COLUMN,
    CREATE_COLUMN_COMMENT,
    MODIFY_COLUMN,
    DROP_COLUMN,

    CREATE_PRIMARY_KEY,
    CREATE_IMPORTED_KEY,
    CREATE_CHECK_CONSTRAINT,
    DROP_PRIMARY_KEY,
    DROP_CONSTRAINT,

    CREATE_INDEX,
    DROP_INDEX,

    CREATE_TRIGGER,
    DROP_TRIGGER,

    CREATE_SEQUENCE,
    DROP_SEQUENCE
}
